config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }

  root 'home#index'

  resources :complaints
  resources :admins
end

app/models/complaint.rb
class Complaint < ApplicationRecord
  belongs_to :user

  enum status: [:ongoing, :resolved]
  validates :title, presence: true
  validates :desc, presence: true
end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :set_complaint, only: %i[ show edit update destroy ], if: Proc.new{ current_user.role== "user" }
  before_action :admin_call,only: %i[show edit update destroy], if: Proc.new{ current_user.role== "admin" }

  # GET /complaints or /complaints.json
  def index
    @complaints = current_user.complaints.all
  end

  # GET /complaints/1 or /complaints/1.json
  def show
  end

  # GET /complaints/new
  def new
    @complaint = current_user.complaints.build
  end

  # GET /complaints/1/edit
  def edit
  end

  # POST /complaints or /complaints.json
  def create
    @complaint = current_user.complaints.build(complaint_params)

    respond_to do |format|
      if @complaint.save
        format.html { redirect_to @complaint, notice: "Complaint was successfully created." }
        format.json { render :show, status: :created, location: @complaint }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @complaint.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /complaints/1 or /complaints/1.json
  def update
    respond_to do |format|
      if @complaint.update(complaint_params)
        format.html { redirect_to @complaint, notice: "Complaint was successfully updated." }
        format.json { render :show, status: :ok, location: @complaint }
      end
    end
  end

  # DELETE /complaints/1 or /complaints/1.json
  def destroy
    @complaint.destroy
    respond_to do |format|
      format.html { redirect_to complaints_url, notice: "Complaint was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_complaint
      @complaint = current_user.complaints.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def complaint_params
      params.require(:complaint).permit(:title, :desc, :status)
    end

    def admin_call
      @complaint = Complaint.find(params[:id])
    end
end

app/helpers/complaints_helper.rb
module ComplaintsHelper
end

app/views/complaints/_form.html.erb
<%= form_with(model: complaint, local: true) do |form| %>
  <% if complaint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(complaint.errors.count, "error") %> prohibited this complaint from being saved:</h2>

      <ul>
        <% complaint.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field ml-5 mt-4 col-md-2">
    <%= form.label :title, class: "h5 text-muted" %>
    <%= form.text_field :title, class:"form-control", autofocus: true, autocomplete: "title" %>
  </div>

  <div class="field ml-5 mt-4 col-md-2">
    <%= form.label :desc, class: "h5 text-muted" %>
    <%= form.text_area :desc, class:"form-control", autofocus: true, autocomplete: "desc" %>
  </div>

  <div class="actions mt-4 ml-5 col-md-3 d-flex">
    <%= form.submit class:"btn col-md-5 btn-primary text-white form-control" %>
    <%= link_to 'Back', complaints_path, class: "btn ml-3 col-md-2 btn-secondary form-control" %>
  </div>


<% end %>

app/views/complaints/edit.html.erb
<h1 class="h2 text-info ml-5 mt-5">Edit Complaint</h1>

<%= render 'form', complaint: @complaint %>

app/views/complaints/index.html.erb
<h1 class="text-center text-info"> User Page </h1>

<h2 class="text-info mt-4 ml-5">My Complaints</h2>

<% if @complaints.count == 0 %>
<a class="text-warning ml-5"><%= "No Complaints Left here" %> </a> 
<% else %>
<table class="table table-striped table-bordered">
  <thead class="thead-dark">
    <tr>
      <th class="text-center">Title</th>
      <th class="text-center">Description</th>
      <th class="text-center">Status</th>
      <th class="text-center" colspan="3"> Actions </th>
    </tr>
  </thead>

  <tbody>
    <% @complaints.each do |complaint| %>
      <tr>
        <td><%= complaint.title %></td>
        <td><%= complaint.desc %></td>
        <td><%= complaint.status %></td>
        <td><%= link_to 'Show', complaint %></td>
        <td><%= link_to 'Edit', edit_complaint_path(complaint) %></td>
        <td><%= link_to 'Destroy', complaint, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

app/views/complaints/new.html.erb
<h2 class="text-info ml-5 mt-5">New Complaint</h2>

<%= render 'form', complaint: @complaint %>

app/views/complaints/show.html.erb
<div class="h2 ml-5 mt-5 text-info">
	Complaint Details
</div>

<p class="h5 ml-5 mt-4">
  <strong>Title:</strong>
  <%= @complaint.title %>
</p>

<p class="h5 ml-5">
  <strong>Desc:</strong>
  <%= @complaint.desc %>
</p>

<p class="h5 ml-5">
  <strong>Status:</strong>
  <%= @complaint.status %>
</p>

<div class="h5 ml-5 mt-4">
  <%= link_to 'Edit', edit_complaint_path(@complaint) %> |
  <%= link_to 'Back', complaints_path %> |
  <%= link_to 'Delete complaint', complaint_path(@complaint), method: :delete, data: { confirm: "Are you sure?" } %>
</div>